import path from "path";

export function generateReadme(report) {
  const s = report.summary;
  const name = path.basename(report.root);

  const stack = [];
  if (s.containsNode) stack.push("Node.js");
  if (s.containsReact) stack.push("React");
  if (s.containsNext) stack.push("Next.js");
  if (s.containsPython) stack.push("Python");
  const stackLine = stack.length ? stack.join(" + ") : "General";

  return `# ${name}

Auto-generated by **AstraFlux Repo Auditor**.

## Overview
This repository is prepared to be **GitHub-ready** and **deploy-ready**.
Detected Stack: **${stackLine}**

## Getting Started

### Prerequisites
- Node.js 18+
${s.containsPython ? "- Python 3.10+\n" : ""}

### Install & Run (Node)
\`\`\`bash
npm install
npm start
\`\`\`

${s.containsPython ? `### Python Setup (if applicable)
\`\`\`bash
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
\`\`\`
` : ""}

## Development
- Live error debugging via **AstraFlux**:
  - Run \`npm start\` to start dashboard at http://localhost:8080
  - Send errors to \`POST /log\` (see \`client/logger.js\`)

## Deploy
- Dockerfile included. Example:
\`\`\`bash
docker build -t ${name.toLowerCase()} .
docker run -p 8080:8080 ${name.toLowerCase()}
\`\`\`

## CI/CD
- GitHub Actions workflow at \`.github/workflows/ci.yml\` runs basic checks.

## Notes
This README was generated based on repository contents. You can edit it as needed.
`;
}
